FROM golang:1.23

RUN apt-get update && apt-get install -y iputils-ping default-mysql-client && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

RUN go mod download
RUN go build -o main .

CMD ["./wait-for-it.sh", "db:3306", "--", "go", "run", "."]