FROM golang:1.23 as builder

RUN apt-get update && apt-get install -y iputils-ping default-mysql-client && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN go mod download
RUN go build -o main .

FROM alpine:latest
RUN apk add --update --no-cache bash go

WORKDIR /app
COPY wait-for-it.sh /app/wait-for-it.sh
COPY --from=builder /app/wait-for-it.sh ./

CMD ["./wait-for-it.sh", "db:3306", "--", "go", "run", "."]
