version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - "80:80"
    networks:
      webnet:
        ipv4_address: 172.16.238.10
    volumes:
      - ../src/Auth:/usr/share/nginx/html/Auth:ro
      - ../src/css:/usr/share/nginx/html/css:ro
      - ../src/JsFiles:/usr/share/nginx/html/JsFiles:ro
      - ../src/templates:/usr/share/nginx/html/templates:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  jwt:
    build:
      context: ./jwt
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      webnet:
        ipv4_address: 172.16.238.11
    volumes:
      - ./jwt:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=auth_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      webnet:
        ipv4_address: 172.16.238.13
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: auth_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro

  content:
    build:
      context: ./content
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      webnet:
        ipv4_address: 172.16.238.12
    volumes:
      - ./content:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=auth_db
    depends_on:
      - db

volumes:
  db_data:

networks:
  webnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
